### PR TITLE
nginx: update ssl config

### PR DESCRIPTION
**Pull request by shivaken**
disable TLS1.0/1.1
update cipher suites config

### CODE REVIEW

**Comment by ip1981** [comment]
Hi Kenichi! :)

**Comment by shivaken** [comment]
Hi Igor, long time no see :)

**Comment by ip1981** [comment]
I think this a good move anyway, just wanted to note that AFAIK nginx and client should agree on protocol, and if a client wants TLS 1.2 only, it will be used. The second note, these options are reasonable defaults that can be overridden in the `server` sections.

**Comment by shivaken** [comment]
I have just removed `ssl_cipher` directive, because it should be configured by user of Nixsap.

**Pull request merged**
